### ISSUE TITLE
503 Error - After install

### ISSUE THREAD

**Issue by jdv68** [fuzziebrain/stackscripts#1]
Thanks for the StackScript!  I created a VM (Linode) using the stackscript.  Lora appeared to run normally and completed, but I'm getting SSL errors and a 503 Service unavailable error after running the scripts.

I've tried updating the SSL cert after correcting the FQDN and fixing my domain records, but certbot can't connect.  Any thoughts?

**Comment by jdv68** [comment]
After the script finished.  I updated the hostname and hosts file to correct the server name and also validated the DNS A/AAAA records.  I also added a CAA record to allow letsencrypt.com to issue the cert.

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: www.centralsw.com
   Type:   unauthorized
   Detail: Invalid response from
   https://www.centralsw.com//.well-known/acme-challenge/wPta7eAk8H-dWiU86G9wQ-GJUeqTzPxba8BlCoHMFcY
   [45.79.221.160]: "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML
   2.0//EN\">\n<html><head>\n<title>404 Not
   Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p"






After creating using stackscript 

503 Service Unavailable
The connection pool named: |apex|| is not correctly configured, due to the following error(s): IO Error: The Network Adapter could not establish the connection   

To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address.

**Comment by jdv68** [comment]
I was also providing /usr/share/tomcat as the webroot for certbot.

**Comment by fuzziebrain** [comment]
@jdv68 What version of the database did you attempt to install?

**Comment by jdv68** [comment]
I used 18.1.0.1 64-bit

https://www.dropbox.com/s/rerpga0xyurhokt/oracle-database-xe-18c-1.0-1.x86_64.rpm?dl=0

**Comment by jdv68** [comment]
Apex 18.2

https://www.dropbox.com/s/bfn69qly3own6ht/apex_18.2.zip?dl=0

ORDS 18.3

https://www.dropbox.com/s/3fepp85qoj4w5q3/ords-18.3.0.270.1456.zip?dl=0

**Comment by fuzziebrain** [comment]
@jdv68 Are you able to validate that the database was installed and configured correctly by the script? I have to apologise. I won't be able to really look into this until after Kscope. Hope that's okay.

**Comment by jdv68** [comment]
It does look like it's running.  No problems waiting.  I appreciate the help.  Have a great Kscope!

**Comment by hanielburton** [comment]
@jdv68 I was having the same issue, but on DigitalOcean. What I found was that the issue only occurred when running ORDS on Tomcat, but running ORDS in Standalone mode worked just fine with the same settings. 

After turning debug mode on in ORDS, I saw these Java exceptions in the stack trace: 

> Caused by: java.io.IOException: Permission denied, socket connect lapse 6 ms. /0.0.0.0 1521 1500 1 true
	at oracle.net.nt.TcpNTAdapter.connect(TcpNTAdapter.java:229)
	at oracle.net.nt.ConnOption.connect(ConnOption.java:172)
	at oracle.net.nt.ConnStrategy.execute(ConnStrategy.java:508)
	... 61 more
Caused by: java.net.SocketException: Permission denied
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:454)
	at sun.nio.ch.Net.connect(Net.java:446)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at java.nio.channels.SocketChannel.open(SocketChannel.java:189)
	at oracle.net.nt.TimeoutSocketChannel.connect(TimeoutSocketChannel.java:108)
	at oracle.net.nt.TimeoutSocketChannel.<init>(TimeoutSocketChannel.java:86)
	at oracle.net.nt.TcpNTAdapter.connect(TcpNTAdapter.java:188)
	... 63 more

To turn debug tracing on: [https://docs.oracle.com/en/database/oracle/oracle-rest-data-services/18.3/aelig/troubleshooting-REST.html#GUID-459D10EB-4E62-4D28-92EB-BE1886615E00](url)

In my case SELINUX is blocking Java from connecting to port 1521. 

Run this to check if that's the case for you: 

`cat /var/log/audit/audit.log | grep denied`

If so, you should see something like this: 

`type=AVC msg=audit(1561154618.063:2909): avc:  denied  { name_connect } for  pid=32318 comm="java" dest=1521 scontext=system_u:system_r:tomcat_t:s0 tcontext=system_u:object_r:oracle_port_t:s0 tclass=tcp_socket permissive=0`

To confirm, temporarily set SELINUX to permissive mode:

`setenforce 0`

Then restart Tomcat and see if that at least changes your debug messages. 

I'm not very familiar with SELINUX so I'll have to research some more on how to allow that connection to the database from Tomcat. 

In the meantime, I'm just running ORDS in Standalone mode.

**Comment by hanielburton** [comment]
Redeployed to a brand new Linode and had the same issue, 503 ORDS message on a fresh install. 

Ran `setsebool -P tomcat_can_network_connect_db 1` then restarted Tomcat and the APEX login page came right up. 

Seems like it's due to new SELinux policy booleans in  RHEL/CentOS 7.6: [https://dev.to/goober99/selinux-has-a-ui-problem-4knj](url)

**Comment by jdv68** [comment]
Thanks.  I'll check that out this afternoon.

**Comment by fuzziebrain** [comment]
Thanks @hanielburton . I'll add and test the additional boolean flag for SELinux. It was a pleasure meeting you at Kscope19!

**Comment by jdv68** [comment]
Thanks!  @hanielburton 

I ran setsebool -P tomcat_can_network_connect_db 1, restarted tomcat it and the APEX login came right up.

@fuzziebrain If you need a tester, please let me know.  I'll be happy to help.
